settings:
  inputFile: 'test.js'       # Where the file to be compiled is located (include .js)
  outputFile: 'test1.js'     # Where the compiled code with be written (include .js)
  curly: inline              # inline or newline
  functionSpacing: 1         # integer