settings:
  inputFile: 'test.js'       # Where the file to be compiled is located (include .js)
  outputFile: 'output.js'    # Where the compiled code with be written (include .js)
  curly: newline              # inline or newline
  functionSpacing: 1         # integer